style:
  WildcardImport:
    active: true
    excludeImports:
      - 'java.util.*'
      - 'org.mockito.Mockito.*'
      - 'org.junit.jupiter.api.Assertions.*'
  ReturnCount:
    active: false
complexity:
  TooManyFunctions:
    active: false